### ISSUE TITLE
KeyError: 'Sampler is not in the sampler registry'

### ISSUE THREAD

**Issue by Ultraman0729** [lexisnexis-risk-open-source/ledetection#6] opened 2023-04-21 14:09 UTC
After setting up according to the environment you provided, run and report an error KeyError: 'Sampler is not in the sampler registry'

**Comment by vuptran** [comment] 2023-04-21 15:44
Which configuration are you trying to run? Can you post the error log?

**Comment by Ultraman0729** [comment] 2023-04-24 05:36
I am using Anaconda Environment, followed the process to complete 8 steps, but reported the error just now.

**Comment by vuptran** [comment] 2023-04-24 15:44
It sounds like you run into this issue when trying to train a model. Which model config are you using? Are you able to `import ledet` within Python? It's hard to address your issue without additional information or a detailed error log.

**Comment by Ultraman0729** [comment] 2023-04-25 06:11
``fatal: not a git repository (or any parent up to mount point /root)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "tools/train.py", line 210, in <module>
    main()
  File "tools/train.py", line 196, in main
    train_detector(
  File "/root/autodl-tmp/ledet/apis/train.py", line 71, in train_detector
    data_loaders = [
  File "/root/autodl-tmp/ledet/apis/train.py", line 72, in <listcomp>
    build_dataloader(
  File "/root/autodl-tmp/ledet/datasets/builder.py", line 78, in build_dataloader
    build_sampler(sampler_cfg, default_args=default_sampler_cfg)
  File "/root/autodl-tmp/ledet/datasets/builder.py", line 47, in build_sampler
    return build_from_cfg(cfg, SAMPLERS, default_args)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'Sampler is not in the sampler registry'

**Comment by vuptran** [comment] 2023-04-25 15:16
Did you run into this issue when trying to train a model using 1 GPU and the utility script `tools/train.py`? If so, I was able to reproduce your behavior. To get around this bug for now, could you try running your model like the following instead:
```bash
export CUDA_VISIBLE_DEVICES=0
bash tools/dist_train.sh /PATH/TO/CONFIG 1
```

**Comment by Ultraman0729** [comment] 2023-04-26 05:02
Thank you very much, the problem is solved, but I want to know what caused it.

**Comment by Ultraman0729** [comment] 2023-04-26 05:41
Hello, I use the COCO2017 dataset, can you share the tag annotations of the few-shot, thank you very much! ! !

**Comment by vuptran** [comment] 2023-04-26 14:48
We are preparing to release model and data artifacts related to the paper in the near future. I am closing this issue since it is resolved. This was a good issue, thanks for bringing it to our attention.

**Closed as completed by vuptran** 2023-04-26 14:48 UTC
